version: '3.9'
services:
  app:
    image: ghcr.io/algostract/gold-fish-talents:latest
    env_file:
      - .env
    volumes:
      - gold-fish-talents_data:/app/.data
      - gold-fish-talents_static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  typesense:
    image: typesense/typesense:28.0
    command: --data-dir /data
    env_file:
      - .env
    volumes:
      - gold-fish-talents_search-data:/data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  gold-fish-talents_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/gold-fish-talents/.data
  gold-fish-talents_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/gold-fish-talents/static
  gold-fish-talents_search-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/gold-fish-talents/.data

networks:
  internal:
    driver: overlay
